# Generated by Django 4.2 on 2023-05-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('level', models.IntegerField()),
                ('department', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('gender', models.BooleanField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
