# Generated by Django 4.2 on 2023-05-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAffairs', '0003_rename_dateofbirth_student_studentbirthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentBirthDate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentEmail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentGPA',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentGender',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentLevel',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentStatus',
            field=models.CharField(max_length=1),
        ),
    ]
