# Generated by Django 4.2 on 2023-05-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAffairs', '0006_student_id_alter_student_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentStatus',
            field=models.CharField(default='False', max_length=6),
        ),
    ]
