# Generated by Django 4.2 on 2023-05-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAffairs', '0009_alter_student_studentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentDepartment',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentStatus',
            field=models.CharField(blank=True, default='active', max_length=8),
        ),
    ]
