# Generated by Django 4.2 on 2023-05-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAffairs', '0010_alter_student_studentdepartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentPhone',
            field=models.CharField(max_length=13),
        ),
    ]
