# Generated by Django 4.2 on 2023-05-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAffairs', '0012_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentStatus',
            field=models.CharField(blank=True, default='0', max_length=1),
        ),
    ]
