# Generated by Django 4.2.1 on 2023-05-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAffairs', '0014_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userPassword',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=15),
        ),
    ]
