# Generated by Django 4.2 on 2023-05-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAffairs', '0016_rename_password_user_userpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentDepartment',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
